
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
tweets:
    resource: "@TweetsBundle/Controller/"
    type:     annotation
    prefix:   /
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


user_bundle:
    resource: "@UserBundle/Resources/config/routing.yml"

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /secured/connect
facebook_login:
    pattern: /login/check-facebook
google_login:
    path: /login/check-google    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
