<?php

namespace tweet\TweetsBundle\Repository;

/**
 * TalentShowcaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTweetsLikeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getlikes($user_tweets){
        $query = $this->createQueryBuilder('s')
            ->select('count(s.id)')
            ->where('s.user_tweets = :user_tweets')
            ->setParameter('user_tweets',$user_tweets)
        ->getQuery();
        return $query->getSingleScalarResult();
    }
}
