<?php

namespace tweet\UserBundle\Repository;

/**
 * UserFollowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFollowRepository extends \Doctrine\ORM\EntityRepository {

    public function getfollowers($user){
        $query = $this->createQueryBuilder('s')
            ->select('count(s.id)')
            ->where('s.user = :user_id')
            ->setParameter('user_id',$user)
        ->getQuery();
        return $query->getSingleScalarResult();
    }

}
